sudo: required

services:
  - docker

language: python

python:
  - '2.7'
  - '3.5'

env:
  - NEO4J_VERSION=3.3.2
  - NEO4J_VERSION=latest

before_install:
  - docker pull neo4j:$NEO4J_VERSION

install: python setup.py testing

script: python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Lundberg
  password:
    secure: pDqWOp0OZE9/uzRBcuWr/FgsKl7y1cpDW4GdBPRPstVMdJ42G1Vf8n5F+kJrpd8aSmG4G0+tw7iUN+SSn29Zpw3eTNJqClu4eKEILXKXO50Jr+w1c4hgpGrzbwi+q9IEMy0VJ/gTPFFAgJhY82R+Cp+6YZ0FJ6JkmwxpTkVVaTbiCXlDNhzLH7l1O1iWK6UpVORiYgJvuGkNvV7THU+z6KEwfCnXxV38bXhxYJKbBkXlgT5Te712OqEyBxMYAMZB+Pkoju94Dvd3dqBQpOyNUTe451PzVyWY2KZOiXE18/+CqB/es9xfXTH+hThwAGcms60/zmoQIFA0/1MKeze0jaO6Zlp00Djo91KIxQEkNAn93dt3xDhEStSgfqVgKN2tHqTO2gWASc7U3Om1O5CAyHOfOHNLYf1G7PFZDKVPA19pLgidIu7YNcr71jSuGyp2Cbw/o4BdiXiKPhQMYoHpjvxBbCURa1j8XwpxK9lWQymzXEaJrTeW2iHyyKwIOM8xH4oWBoCdAcjdySKx8vkrFnBJZIWd8NIKIp3xPSm0chzU7ohDEJiC1ucN+KUlHOwUW/aLRyQhhiETCdP42Tdw5yyfenhRwA9eVEepmh6V0CZT4JrKjO3lOiM+wdL/xzK8xEV9jwvueE5HFNh7VMF3UGCdEbQTIb3yrE7TelQfzWo=
  on:
    tags: true
    repo: NORDUnet/python-norduniclient
    condition: "$NEO4J_VERSION = 3.3.2"
    python: '2.7'
